#! /usr/local/bin/python3

import sys
import time


if __name__== "__main__":

  input = (int)(sys.argv[1])  

  # Convert from milliseconds to seconds since epoch
  if len(str(input)) == 13:
    input /= 1000

  local_time = time.strftime('%Y-%m-%d %A %H:%M:%S', time.localtime(input))
  gmt_time = time.strftime('%Y-%m-%d %A %H:%M:%S', time.gmtime(input))
  print("Local time     {0}".format(local_time))
  print("Gm time        {0}".format(gmt_time))
